### ISSUE TITLE
Picked up Bombchus, got zero of them?

### ISSUE THREAD

**Issue by pkmnfrk** [az64/mm-rando#8]
Seed: 1253624078
Settings: kqdij2-2rn-lh-16psr

I'm not sure if this is intentional or not, but I picked up bombchus from the Termina Field pillar grotto (what I believe the spoiler log calls "Termina Bombchu Grotto"), and got bombchus in my inventory, but with a count of zero.

![image](https://user-images.githubusercontent.com/1333816/52977584-bd46ec00-339b-11e9-85b0-bad04fbc8f2f.png)

I'm a bit rusty of MM, so perhaps this is intentional (since I don't have the bomb bag), but it seems odd.

**Comment by BladefangFT** [comment]
this is vanilla behaviour. you cannot get any bombchus in vanilla mm without a bomb bag, they turn into blupees. rando shows what you got so you actually know.

**Comment by pkmnfrk** [comment]
Ah, got it. Thanks!
